import type { Facility, Report } from "./types";

export const MOCK_FACILITIES: Facility[] = [
  { id: 1, nama: "Ruang Kelas A101", tipe: "ruang_kelas", lokasi: "Gedung A Lantai 1", kapasitas: 40, status: "aktif" },
  { id: 2, nama: "Ruang Kelas B201", tipe: "ruang_kelas", lokasi: "Gedung B Lantai 2", kapasitas: 35, status: "aktif" },
  { id: 3, nama: "Laboratorium Komputer 1", tipe: "laboratorium", lokasi: "Gedung C Lantai 3", kapasitas: 30, status: "dalam_perbaikan" },
  { id: 4, nama: "Aula Utama", tipe: "aula", lokasi: "Gedung D Lantai 1", kapasitas: 200, status: "aktif" },
  { id: 5, nama: "Lapangan Basket", tipe: "lapangan", lokasi: "Area Olahraga", kapasitas: 50, status: "aktif" },
  { id: 6, nama: "Ruang Rapat 1", tipe: "ruang_kelas", lokasi: "Gedung A Lantai 3", kapasitas: 20, status: "aktif" },
];

export const INITIAL_REPORTS: Report[] = [
  {
    id: 1,
    userId: 1,
    userName: "Andi Pratama",
    facilityId: 1,
    facilityName: "Ruang Kelas A101",
    kategori: "Kerusakan Ringan",
    deskripsi: "Proyektor di ruangan tidak menyala sejak kemarin. Sudah dicoba menyalakan beberapa kali tetapi tidak ada respon. Lampu indikator juga mati.",
    foto: null,
    status: "baru",
    catatanResolusi: null,
    ditanganiOleh: null,
    createdAt: "2026-09-01T09:30:00",
    updatedAt: "2026-09-01T09:30:00",
  },
  {
    id: 2,
    userId: 2,
    userName: "Sari Dewi",
    facilityId: 2,
    facilityName: "Ruang Kelas B201",
    kategori: "Kerusakan Berat",
    deskripsi: "Papan tulis sudah retak di bagian tengah dan tidak bisa digunakan dengan baik. Perlu diganti segera karena mengganggu kegiatan belajar mengajar.",
    foto: null,
    status: "diproses",
    catatanResolusi: null,
    ditanganiOleh: "Budi Santoso",
    createdAt: "2026-08-30T14:15:00",
    updatedAt: "2026-09-01T10:00:00",
  },
  {
    id: 3,
    userId: 3,
    userName: "Rina Wati",
    facilityId: 3,
    facilityName: "Laboratorium Komputer 1",
    kategori: "Kebutuhan Perbaikan Segera",
    deskripsi: "AC tidak dingin sama sekali di lab komputer. Suhu ruangan sangat panas dan tidak nyaman untuk praktikum. Mahasiswa mengeluh kepanasan.",
    foto: "https://fsktm.um.edu.my/fsktm/images/DEV/mm3.JPG",
    status: "selesai",
    catatanResolusi: "Teknisi sudah melakukan perbaikan. Freon sudah diisi ulang dan filter dibersihkan. AC berfungsi normal.",
    ditanganiOleh: "Budi Santoso",
    createdAt: "2026-08-28T08:00:00",
    updatedAt: "2026-08-30T16:00:00",
  },
  {
    id: 4,
    userId: 1,
    userName: "Andi Pratama",
    facilityId: 4,
    facilityName: "Aula Utama",
    kategori: "Pemeliharaan Rutin",
    deskripsi: "Lampu di bagian panggung aula sudah mulai redup dan beberapa sudah mati. Perlu diganti sebelum acara besar minggu depan.",
    foto: null,
    status: "ditolak",
    catatanResolusi: "Laporan ditolak karena lampu yang mati merupakan bagian dari program pemeliharaan rutin yang sudah terjadwal bulan depan.",
    ditanganiOleh: "Budi Santoso",
    createdAt: "2026-08-25T11:00:00",
    updatedAt: "2026-08-27T09:30:00",
  },
  {
    id: 5,
    userId: 2,
    userName: "Sari Dewi",
    facilityId: 5,
    facilityName: "Lapangan Basket",
    kategori: "Lainnya",
    deskripsi: "Tong sampah di dekat lapangan basket sudah penuh dan meluap. Beberapa sampah berserakan di area sekitar lapangan.",
    foto: null,
    status: "baru",
    catatanResolusi: null,
    ditanganiOleh: null,
    createdAt: "2026-09-02T16:45:00",
    updatedAt: "2026-09-02T16:45:00",
  },
  {
    id: 6,
    userId: 3,
    userName: "Rina Wati",
    facilityId: 6,
    facilityName: "Ruang Rapat 1",
    kategori: "Kerusakan Ringan",
    deskripsi: "Saklar lampu di ruang rapat sudah longgar dan terasa tidak stabil saat diputar. Seringkali lampu berkedip karena kontak yang buruk.",
    foto: null,
    status: "baru",
    catatanResolusi: null,
    ditanganiOleh: null,
    createdAt: "2026-09-03T07:10:00",
    updatedAt: "2026-09-03T07:10:00",
  },
];
